import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { NAVBAR_HEIGHT } from '@/config/global-ui-dims';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen overflow-hidden`}
      >
        <Navbar />
        <div
          className="md:container mx-auto sm:px-0 px-4 overflow-x-hidden"
          style={{
            marginTop: NAVBAR_HEIGHT,
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
